"""SAGE 0.2 baseline

Revision ID: 0001_sage_0_2
Revises: 
Create Date: 2026-07-31 15:21:53.806503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_sage_0_2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_capabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('authority', sa.JSON(), nullable=False),
    sa.Column('cost_score', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'agent', name='uq_agent_capability')
    )
    op.create_index(op.f('ix_agent_capabilities_agent'), 'agent_capabilities', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_capabilities_available'), 'agent_capabilities', ['available'], unique=False)
    op.create_index(op.f('ix_agent_capabilities_workspace'), 'agent_capabilities', ['workspace'], unique=False)
    op.create_index('ix_agent_capability_available', 'agent_capabilities', ['workspace', 'available'], unique=False)
    op.create_table('bus_messages',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('packet_id', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=True),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('partition_key', sa.String(length=128), nullable=False),
    sa.Column('ordering_key', sa.String(length=128), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wire', sa.JSON(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=False),
    sa.Column('wire_bytes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'idempotency_key', name='uq_bus_idempotency')
    )
    op.create_index(op.f('ix_bus_messages_correlation_id'), 'bus_messages', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_bus_messages_expires_at'), 'bus_messages', ['expires_at'], unique=False)
    op.create_index(op.f('ix_bus_messages_idempotency_key'), 'bus_messages', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_bus_messages_ordering_key'), 'bus_messages', ['ordering_key'], unique=False)
    op.create_index(op.f('ix_bus_messages_packet_id'), 'bus_messages', ['packet_id'], unique=False)
    op.create_index(op.f('ix_bus_messages_partition_key'), 'bus_messages', ['partition_key'], unique=False)
    op.create_index(op.f('ix_bus_messages_receiver'), 'bus_messages', ['receiver'], unique=False)
    op.create_index(op.f('ix_bus_messages_run_id'), 'bus_messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_bus_messages_sender'), 'bus_messages', ['sender'], unique=False)
    op.create_index(op.f('ix_bus_messages_status'), 'bus_messages', ['status'], unique=False)
    op.create_index(op.f('ix_bus_messages_workspace'), 'bus_messages', ['workspace'], unique=False)
    op.create_index('ix_bus_partition_order', 'bus_messages', ['workspace', 'partition_key', 'ordering_key', 'sequence_no'], unique=False)
    op.create_index('ix_bus_receiver_status_priority', 'bus_messages', ['workspace', 'receiver', 'status', 'priority'], unique=False)
    op.create_index('ix_bus_run_created', 'bus_messages', ['run_id', 'created_at'], unique=False)
    op.create_table('calibration_buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('task_family', sa.String(length=128), nullable=False),
    sa.Column('bucket', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('predicted_sum', sa.Float(), nullable=False),
    sa.Column('observed_sum', sa.Float(), nullable=False),
    sa.Column('squared_error_sum', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'receiver', 'model', 'task_family', 'bucket', name='uq_calibration_bucket')
    )
    op.create_index(op.f('ix_calibration_buckets_model'), 'calibration_buckets', ['model'], unique=False)
    op.create_index(op.f('ix_calibration_buckets_receiver'), 'calibration_buckets', ['receiver'], unique=False)
    op.create_index(op.f('ix_calibration_buckets_task_family'), 'calibration_buckets', ['task_family'], unique=False)
    op.create_index(op.f('ix_calibration_buckets_workspace'), 'calibration_buckets', ['workspace'], unique=False)
    op.create_index('ix_calibration_lookup', 'calibration_buckets', ['workspace', 'receiver', 'model', 'task_family'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codebook', sa.String(length=128), nullable=False),
    sa.Column('canonical', sa.String(length=512), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('estimated_savings_bytes', sa.Integer(), nullable=False),
    sa.Column('max_neighbor_similarity', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codebook', 'canonical', name='uq_candidate_cb_canonical')
    )
    op.create_index(op.f('ix_candidates_codebook'), 'candidates', ['codebook'], unique=False)
    op.create_table('codebook_releases',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('release', sa.String(length=128), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'release', name='uq_codebook_release')
    )
    op.create_index('ix_codebook_release_active', 'codebook_releases', ['namespace', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_codebook_releases_merkle_root'), 'codebook_releases', ['merkle_root'], unique=False)
    op.create_index(op.f('ix_codebook_releases_namespace'), 'codebook_releases', ['namespace'], unique=False)
    op.create_index(op.f('ix_codebook_releases_release'), 'codebook_releases', ['release'], unique=False)
    op.create_index(op.f('ix_codebook_releases_status'), 'codebook_releases', ['status'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codebook', sa.String(length=128), nullable=False),
    sa.Column('canonical', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding_space', sa.String(length=256), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('lsh_bucket', sa.String(length=32), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('semantic_hash', sa.String(length=64), nullable=False),
    sa.Column('replacement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['replacement_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codebook', 'canonical', name='uq_concept_codebook_canonical')
    )
    op.create_index(op.f('ix_concepts_codebook'), 'concepts', ['codebook'], unique=False)
    op.create_index('ix_concepts_codebook_count', 'concepts', ['codebook', 'seen_count'], unique=False)
    op.create_index(op.f('ix_concepts_embedding_space'), 'concepts', ['embedding_space'], unique=False)
    op.create_index(op.f('ix_concepts_lsh_bucket'), 'concepts', ['lsh_bucket'], unique=False)
    op.create_table('federation_peers',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('public_key_b64', sa.Text(), nullable=False),
    sa.Column('allowed_namespaces', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'name', name='uq_federation_peer')
    )
    op.create_index(op.f('ix_federation_peers_name'), 'federation_peers', ['name'], unique=False)
    op.create_index(op.f('ix_federation_peers_workspace'), 'federation_peers', ['workspace'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'operation', 'key', name='uq_idempotency_record')
    )
    op.create_index('ix_idempotency_expiry', 'idempotency_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_expires_at'), 'idempotency_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=False)
    op.create_index(op.f('ix_idempotency_records_operation'), 'idempotency_records', ['operation'], unique=False)
    op.create_index(op.f('ix_idempotency_records_workspace'), 'idempotency_records', ['workspace'], unique=False)
    op.create_table('information_flow_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('object_kind', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'object_kind', 'object_id', 'label', name='uq_information_flow_label')
    )
    op.create_index(op.f('ix_information_flow_labels_label'), 'information_flow_labels', ['label'], unique=False)
    op.create_index(op.f('ix_information_flow_labels_object_id'), 'information_flow_labels', ['object_id'], unique=False)
    op.create_index(op.f('ix_information_flow_labels_object_kind'), 'information_flow_labels', ['object_kind'], unique=False)
    op.create_index(op.f('ix_information_flow_labels_workspace'), 'information_flow_labels', ['workspace'], unique=False)
    op.create_index('ix_information_flow_object', 'information_flow_labels', ['workspace', 'object_kind', 'object_id'], unique=False)
    op.create_table('message_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('packet_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('sender', sa.String(length=128), nullable=True),
    sa.Column('receiver', sa.String(length=128), nullable=True),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('input_bytes', sa.Integer(), nullable=False),
    sa.Column('output_bytes', sa.Integer(), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=False),
    sa.Column('budget_tokens', sa.Integer(), nullable=True),
    sa.Column('atom_count', sa.Integer(), nullable=False),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('packet', sa.JSON(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('task_success', sa.Float(), nullable=True),
    sa.Column('semantic_loss_score', sa.Float(), nullable=False),
    sa.Column('original_token_estimate', sa.Integer(), nullable=False),
    sa.Column('receiver_known_ratio', sa.Float(), nullable=False),
    sa.Column('pattern_count', sa.Integer(), nullable=False),
    sa.Column('ref_bytes_avoided', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_audit_packet_id'), 'message_audit', ['packet_id'], unique=True)
    op.create_index(op.f('ix_message_audit_run_id'), 'message_audit', ['run_id'], unique=False)
    op.create_index(op.f('ix_message_audit_workspace'), 'message_audit', ['workspace'], unique=False)
    op.create_index('ix_message_run_created', 'message_audit', ['run_id', 'created_at'], unique=False)
    op.create_index('ix_message_sender_receiver', 'message_audit', ['sender', 'receiver'], unique=False)
    op.create_table('model_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('runtime', sa.String(length=128), nullable=False),
    sa.Column('runtime_version', sa.String(length=128), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'receiver', 'identity_hash', name='uq_model_identity')
    )
    op.create_index(op.f('ix_model_identities_active'), 'model_identities', ['active'], unique=False)
    op.create_index(op.f('ix_model_identities_identity_hash'), 'model_identities', ['identity_hash'], unique=False)
    op.create_index(op.f('ix_model_identities_receiver'), 'model_identities', ['receiver'], unique=False)
    op.create_index(op.f('ix_model_identities_workspace'), 'model_identities', ['workspace'], unique=False)
    op.create_index('ix_model_identity_active', 'model_identities', ['workspace', 'receiver', 'active'], unique=False)
    op.create_table('ordering_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('ordering_key', sa.String(length=128), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'ordering_key', name='uq_ordering_counter')
    )
    op.create_index(op.f('ix_ordering_counters_ordering_key'), 'ordering_counters', ['ordering_key'], unique=False)
    op.create_index(op.f('ix_ordering_counters_workspace'), 'ordering_counters', ['workspace'], unique=False)
    op.create_table('pattern_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codebook', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('canonical', sa.Text(), nullable=False),
    sa.Column('composition', sa.JSON(), nullable=False),
    sa.Column('relation_structure', sa.JSON(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('estimated_savings_bytes', sa.Integer(), nullable=False),
    sa.Column('semantic_variance', sa.Float(), nullable=False),
    sa.Column('slot_samples', sa.JSON(), nullable=False),
    sa.Column('trust_scope', sa.String(length=32), nullable=False),
    sa.Column('source_diversity', sa.Integer(), nullable=False),
    sa.Column('dominant_source_share', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codebook', 'signature', name='uq_pattern_candidate_signature')
    )
    op.create_index('ix_pattern_candidate_rank', 'pattern_candidates', ['codebook', 'occurrence_count', 'estimated_savings_bytes'], unique=False)
    op.create_index(op.f('ix_pattern_candidates_codebook'), 'pattern_candidates', ['codebook'], unique=False)
    op.create_index(op.f('ix_pattern_candidates_signature'), 'pattern_candidates', ['signature'], unique=False)
    op.create_index(op.f('ix_pattern_candidates_trust_scope'), 'pattern_candidates', ['trust_scope'], unique=False)
    op.create_table('pattern_source_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codebook', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codebook', 'signature', 'source_hash', name='uq_pattern_source_evidence')
    )
    op.create_index(op.f('ix_pattern_source_evidence_codebook'), 'pattern_source_evidence', ['codebook'], unique=False)
    op.create_index(op.f('ix_pattern_source_evidence_signature'), 'pattern_source_evidence', ['signature'], unique=False)
    op.create_index(op.f('ix_pattern_source_evidence_source_hash'), 'pattern_source_evidence', ['source_hash'], unique=False)
    op.create_index('ix_pattern_source_signature', 'pattern_source_evidence', ['codebook', 'signature'], unique=False)
    op.create_table('quota_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'resource', 'window_start', name='uq_quota_counter')
    )
    op.create_index(op.f('ix_quota_counters_resource'), 'quota_counters', ['resource'], unique=False)
    op.create_index(op.f('ix_quota_counters_window_start'), 'quota_counters', ['window_start'], unique=False)
    op.create_index(op.f('ix_quota_counters_workspace'), 'quota_counters', ['workspace'], unique=False)
    op.create_index('ix_quota_workspace_resource', 'quota_counters', ['workspace', 'resource', 'window_start'], unique=False)
    op.create_table('receiver_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('current_state', sa.String(length=80), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'receiver', name='uq_receiver_knowledge')
    )
    op.create_index(op.f('ix_receiver_knowledge_receiver'), 'receiver_knowledge', ['receiver'], unique=False)
    op.create_index(op.f('ix_receiver_knowledge_workspace'), 'receiver_knowledge', ['workspace'], unique=False)
    op.create_table('receiver_knowledge_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'receiver', 'kind', 'value', name='uq_receiver_knowledge_item')
    )
    op.create_index('ix_receiver_item_lookup', 'receiver_knowledge_items', ['workspace', 'receiver', 'kind'], unique=False)
    op.create_index(op.f('ix_receiver_knowledge_items_kind'), 'receiver_knowledge_items', ['kind'], unique=False)
    op.create_index(op.f('ix_receiver_knowledge_items_receiver'), 'receiver_knowledge_items', ['receiver'], unique=False)
    op.create_index(op.f('ix_receiver_knowledge_items_value'), 'receiver_knowledge_items', ['value'], unique=False)
    op.create_index(op.f('ix_receiver_knowledge_items_workspace'), 'receiver_knowledge_items', ['workspace'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ciphertext', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('acl', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_expires_at'), 'references', ['expires_at'], unique=False)
    op.create_index(op.f('ix_references_tier'), 'references', ['tier'], unique=False)
    op.create_index(op.f('ix_references_workspace'), 'references', ['workspace'], unique=False)
    op.create_table('semantic_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('packet', sa.JSON(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('codebook_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('semantic_facts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('predicate', sa.String(length=256), nullable=False),
    sa.Column('object', sa.JSON(), nullable=False),
    sa.Column('epistemic_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('sensitivity', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fact_source', 'semantic_facts', ['workspace', 'source'], unique=False)
    op.create_index('ix_fact_subject_predicate', 'semantic_facts', ['workspace', 'subject', 'predicate', 'status'], unique=False)
    op.create_index(op.f('ix_semantic_facts_epistemic_type'), 'semantic_facts', ['epistemic_type'], unique=False)
    op.create_index(op.f('ix_semantic_facts_predicate'), 'semantic_facts', ['predicate'], unique=False)
    op.create_index(op.f('ix_semantic_facts_source'), 'semantic_facts', ['source'], unique=False)
    op.create_index(op.f('ix_semantic_facts_status'), 'semantic_facts', ['status'], unique=False)
    op.create_index(op.f('ix_semantic_facts_subject'), 'semantic_facts', ['subject'], unique=False)
    op.create_index(op.f('ix_semantic_facts_workspace'), 'semantic_facts', ['workspace'], unique=False)
    op.create_table('shared_states',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('parent_id', sa.String(length=80), nullable=True),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['shared_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_states_workspace'), 'shared_states', ['workspace'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_workspace_agent', 'subscriptions', ['workspace', 'agent', 'active'], unique=False)
    op.create_index(op.f('ix_subscriptions_active'), 'subscriptions', ['active'], unique=False)
    op.create_index(op.f('ix_subscriptions_agent'), 'subscriptions', ['agent'], unique=False)
    op.create_index(op.f('ix_subscriptions_workspace'), 'subscriptions', ['workspace'], unique=False)
    op.create_table('concept_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codebook', sa.String(length=128), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codebook', 'alias', name='uq_concept_alias')
    )
    op.create_index(op.f('ix_concept_aliases_codebook'), 'concept_aliases', ['codebook'], unique=False)
    op.create_index(op.f('ix_concept_aliases_concept_id'), 'concept_aliases', ['concept_id'], unique=False)
    op.create_table('contradictions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('left_fact_id', sa.String(length=80), nullable=False),
    sa.Column('right_fact_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['left_fact_id'], ['semantic_facts.id'], ),
    sa.ForeignKeyConstraint(['right_fact_id'], ['semantic_facts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left_fact_id', 'right_fact_id', name='uq_contradiction_pair')
    )
    op.create_index('ix_contradiction_status', 'contradictions', ['workspace', 'status'], unique=False)
    op.create_index(op.f('ix_contradictions_left_fact_id'), 'contradictions', ['left_fact_id'], unique=False)
    op.create_index(op.f('ix_contradictions_right_fact_id'), 'contradictions', ['right_fact_id'], unique=False)
    op.create_index(op.f('ix_contradictions_status'), 'contradictions', ['status'], unique=False)
    op.create_index(op.f('ix_contradictions_workspace'), 'contradictions', ['workspace'], unique=False)
    op.create_table('fact_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_fact_id', sa.String(length=80), nullable=False),
    sa.Column('child_fact_id', sa.String(length=80), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_fact_id'], ['semantic_facts.id'], ),
    sa.ForeignKeyConstraint(['parent_fact_id'], ['semantic_facts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_fact_id', 'child_fact_id', name='uq_fact_dependency')
    )
    op.create_index(op.f('ix_fact_dependencies_child_fact_id'), 'fact_dependencies', ['child_fact_id'], unique=False)
    op.create_index(op.f('ix_fact_dependencies_parent_fact_id'), 'fact_dependencies', ['parent_fact_id'], unique=False)
    op.create_index('ix_fact_dependency_parent', 'fact_dependencies', ['parent_fact_id'], unique=False)
    op.create_table('learned_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codebook', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('canonical', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('composition', sa.JSON(), nullable=False),
    sa.Column('relation_structure', sa.JSON(), nullable=False),
    sa.Column('embedding_space', sa.String(length=256), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('estimated_savings_bytes', sa.Integer(), nullable=False),
    sa.Column('semantic_variance', sa.Float(), nullable=False),
    sa.Column('slot_samples', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('shadow_samples', sa.Integer(), nullable=False),
    sa.Column('shadow_success_sum', sa.Float(), nullable=False),
    sa.Column('task_success_count', sa.Integer(), nullable=False),
    sa.Column('task_success_sum', sa.Float(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('utility_score', sa.Float(), nullable=False),
    sa.Column('ambiguity_score', sa.Float(), nullable=False),
    sa.Column('interoperability_score', sa.Float(), nullable=False),
    sa.Column('calibrated_reliability', sa.Float(), nullable=False),
    sa.Column('trust_scope', sa.String(length=32), nullable=False),
    sa.Column('source_diversity', sa.Integer(), nullable=False),
    sa.Column('dominant_source_share', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooling_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codebook', 'signature', name='uq_learned_pattern_signature'),
    sa.UniqueConstraint('concept_id', name='uq_learned_pattern_concept')
    )
    op.create_index('ix_learned_pattern_status', 'learned_patterns', ['codebook', 'status', 'occurrence_count'], unique=False)
    op.create_index(op.f('ix_learned_patterns_codebook'), 'learned_patterns', ['codebook'], unique=False)
    op.create_index(op.f('ix_learned_patterns_concept_id'), 'learned_patterns', ['concept_id'], unique=False)
    op.create_index(op.f('ix_learned_patterns_embedding_space'), 'learned_patterns', ['embedding_space'], unique=False)
    op.create_index(op.f('ix_learned_patterns_signature'), 'learned_patterns', ['signature'], unique=False)
    op.create_index(op.f('ix_learned_patterns_status'), 'learned_patterns', ['status'], unique=False)
    op.create_index(op.f('ix_learned_patterns_trust_scope'), 'learned_patterns', ['trust_scope'], unique=False)
    op.create_table('reference_grants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_id', sa.String(length=80), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('acl', sa.JSON(), nullable=False),
    sa.Column('allowed_paths', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('sensitivity', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ref_id'], ['references.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_id', 'workspace', 'owner', name='uq_reference_grant_owner')
    )
    op.create_index('ix_reference_grant_lookup', 'reference_grants', ['workspace', 'ref_id'], unique=False)
    op.create_index(op.f('ix_reference_grants_expires_at'), 'reference_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_reference_grants_owner'), 'reference_grants', ['owner'], unique=False)
    op.create_index(op.f('ix_reference_grants_ref_id'), 'reference_grants', ['ref_id'], unique=False)
    op.create_index(op.f('ix_reference_grants_tier'), 'reference_grants', ['tier'], unique=False)
    op.create_index(op.f('ix_reference_grants_workspace'), 'reference_grants', ['workspace'], unique=False)
    op.create_table('state_checkpoints',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('state_id', sa.String(length=80), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['shared_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'state_id', name='uq_state_checkpoint_state')
    )
    op.create_index('ix_state_checkpoint_workspace_created', 'state_checkpoints', ['workspace', 'created_at'], unique=False)
    op.create_index(op.f('ix_state_checkpoints_payload_hash'), 'state_checkpoints', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_state_checkpoints_state_id'), 'state_checkpoints', ['state_id'], unique=False)
    op.create_index(op.f('ix_state_checkpoints_workspace'), 'state_checkpoints', ['workspace'], unique=False)
    op.create_table('pattern_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_pattern_id', sa.Integer(), nullable=False),
    sa.Column('child_pattern_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_pattern_id'], ['learned_patterns.id'], ),
    sa.ForeignKeyConstraint(['parent_pattern_id'], ['learned_patterns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_pattern_id', 'child_pattern_id', 'position', name='uq_pattern_edge')
    )
    op.create_index('ix_pattern_edge_parent', 'pattern_edges', ['parent_pattern_id', 'position'], unique=False)
    op.create_index(op.f('ix_pattern_edges_child_pattern_id'), 'pattern_edges', ['child_pattern_id'], unique=False)
    op.create_index(op.f('ix_pattern_edges_parent_pattern_id'), 'pattern_edges', ['parent_pattern_id'], unique=False)
    op.create_table('pattern_receiver_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('full_success_sum', sa.Float(), nullable=False),
    sa.Column('compressed_success_sum', sa.Float(), nullable=False),
    sa.Column('fidelity_sum', sa.Float(), nullable=False),
    sa.Column('exact_equivalence_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['learned_patterns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_id', 'workspace', 'receiver', 'model', name='uq_pattern_receiver_metric')
    )
    op.create_index('ix_pattern_receiver_lookup', 'pattern_receiver_metrics', ['workspace', 'receiver', 'model'], unique=False)
    op.create_index(op.f('ix_pattern_receiver_metrics_model'), 'pattern_receiver_metrics', ['model'], unique=False)
    op.create_index(op.f('ix_pattern_receiver_metrics_pattern_id'), 'pattern_receiver_metrics', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_pattern_receiver_metrics_receiver'), 'pattern_receiver_metrics', ['receiver'], unique=False)
    op.create_index(op.f('ix_pattern_receiver_metrics_workspace'), 'pattern_receiver_metrics', ['workspace'], unique=False)
    op.create_table('pattern_validation_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('model_identity_hash', sa.String(length=64), nullable=False),
    sa.Column('task_family', sa.String(length=128), nullable=False),
    sa.Column('full_success', sa.Float(), nullable=False),
    sa.Column('compressed_success', sa.Float(), nullable=False),
    sa.Column('fidelity', sa.Float(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['learned_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_validation_evidence_model_identity_hash'), 'pattern_validation_evidence', ['model_identity_hash'], unique=False)
    op.create_index(op.f('ix_pattern_validation_evidence_pattern_id'), 'pattern_validation_evidence', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_pattern_validation_evidence_receiver'), 'pattern_validation_evidence', ['receiver'], unique=False)
    op.create_index(op.f('ix_pattern_validation_evidence_source_hash'), 'pattern_validation_evidence', ['source_hash'], unique=False)
    op.create_index(op.f('ix_pattern_validation_evidence_split'), 'pattern_validation_evidence', ['split'], unique=False)
    op.create_index(op.f('ix_pattern_validation_evidence_task_family'), 'pattern_validation_evidence', ['task_family'], unique=False)
    op.create_index(op.f('ix_pattern_validation_evidence_workspace'), 'pattern_validation_evidence', ['workspace'], unique=False)
    op.create_index('ix_pattern_validation_pattern_split', 'pattern_validation_evidence', ['pattern_id', 'split', 'created_at'], unique=False)
    op.create_index('ix_pattern_validation_receiver_model', 'pattern_validation_evidence', ['workspace', 'receiver', 'model_identity_hash'], unique=False)
    op.create_table('reliability_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace', sa.String(length=128), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=False),
    sa.Column('model_identity_hash', sa.String(length=64), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('task_family', sa.String(length=128), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('fidelity_sum', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['learned_patterns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace', 'receiver', 'model_identity_hash', 'pattern_id', 'task_family', 'window_start', name='uq_reliability_window')
    )
    op.create_index('ix_reliability_drift', 'reliability_windows', ['workspace', 'receiver', 'model_identity_hash', 'status'], unique=False)
    op.create_index(op.f('ix_reliability_windows_model_identity_hash'), 'reliability_windows', ['model_identity_hash'], unique=False)
    op.create_index(op.f('ix_reliability_windows_pattern_id'), 'reliability_windows', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_reliability_windows_receiver'), 'reliability_windows', ['receiver'], unique=False)
    op.create_index(op.f('ix_reliability_windows_status'), 'reliability_windows', ['status'], unique=False)
    op.create_index(op.f('ix_reliability_windows_task_family'), 'reliability_windows', ['task_family'], unique=False)
    op.create_index(op.f('ix_reliability_windows_window_start'), 'reliability_windows', ['window_start'], unique=False)
    op.create_index(op.f('ix_reliability_windows_workspace'), 'reliability_windows', ['workspace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reliability_windows_workspace'), table_name='reliability_windows')
    op.drop_index(op.f('ix_reliability_windows_window_start'), table_name='reliability_windows')
    op.drop_index(op.f('ix_reliability_windows_task_family'), table_name='reliability_windows')
    op.drop_index(op.f('ix_reliability_windows_status'), table_name='reliability_windows')
    op.drop_index(op.f('ix_reliability_windows_receiver'), table_name='reliability_windows')
    op.drop_index(op.f('ix_reliability_windows_pattern_id'), table_name='reliability_windows')
    op.drop_index(op.f('ix_reliability_windows_model_identity_hash'), table_name='reliability_windows')
    op.drop_index('ix_reliability_drift', table_name='reliability_windows')
    op.drop_table('reliability_windows')
    op.drop_index('ix_pattern_validation_receiver_model', table_name='pattern_validation_evidence')
    op.drop_index('ix_pattern_validation_pattern_split', table_name='pattern_validation_evidence')
    op.drop_index(op.f('ix_pattern_validation_evidence_workspace'), table_name='pattern_validation_evidence')
    op.drop_index(op.f('ix_pattern_validation_evidence_task_family'), table_name='pattern_validation_evidence')
    op.drop_index(op.f('ix_pattern_validation_evidence_split'), table_name='pattern_validation_evidence')
    op.drop_index(op.f('ix_pattern_validation_evidence_source_hash'), table_name='pattern_validation_evidence')
    op.drop_index(op.f('ix_pattern_validation_evidence_receiver'), table_name='pattern_validation_evidence')
    op.drop_index(op.f('ix_pattern_validation_evidence_pattern_id'), table_name='pattern_validation_evidence')
    op.drop_index(op.f('ix_pattern_validation_evidence_model_identity_hash'), table_name='pattern_validation_evidence')
    op.drop_table('pattern_validation_evidence')
    op.drop_index(op.f('ix_pattern_receiver_metrics_workspace'), table_name='pattern_receiver_metrics')
    op.drop_index(op.f('ix_pattern_receiver_metrics_receiver'), table_name='pattern_receiver_metrics')
    op.drop_index(op.f('ix_pattern_receiver_metrics_pattern_id'), table_name='pattern_receiver_metrics')
    op.drop_index(op.f('ix_pattern_receiver_metrics_model'), table_name='pattern_receiver_metrics')
    op.drop_index('ix_pattern_receiver_lookup', table_name='pattern_receiver_metrics')
    op.drop_table('pattern_receiver_metrics')
    op.drop_index(op.f('ix_pattern_edges_parent_pattern_id'), table_name='pattern_edges')
    op.drop_index(op.f('ix_pattern_edges_child_pattern_id'), table_name='pattern_edges')
    op.drop_index('ix_pattern_edge_parent', table_name='pattern_edges')
    op.drop_table('pattern_edges')
    op.drop_index(op.f('ix_state_checkpoints_workspace'), table_name='state_checkpoints')
    op.drop_index(op.f('ix_state_checkpoints_state_id'), table_name='state_checkpoints')
    op.drop_index(op.f('ix_state_checkpoints_payload_hash'), table_name='state_checkpoints')
    op.drop_index('ix_state_checkpoint_workspace_created', table_name='state_checkpoints')
    op.drop_table('state_checkpoints')
    op.drop_index(op.f('ix_reference_grants_workspace'), table_name='reference_grants')
    op.drop_index(op.f('ix_reference_grants_tier'), table_name='reference_grants')
    op.drop_index(op.f('ix_reference_grants_ref_id'), table_name='reference_grants')
    op.drop_index(op.f('ix_reference_grants_owner'), table_name='reference_grants')
    op.drop_index(op.f('ix_reference_grants_expires_at'), table_name='reference_grants')
    op.drop_index('ix_reference_grant_lookup', table_name='reference_grants')
    op.drop_table('reference_grants')
    op.drop_index(op.f('ix_learned_patterns_trust_scope'), table_name='learned_patterns')
    op.drop_index(op.f('ix_learned_patterns_status'), table_name='learned_patterns')
    op.drop_index(op.f('ix_learned_patterns_signature'), table_name='learned_patterns')
    op.drop_index(op.f('ix_learned_patterns_embedding_space'), table_name='learned_patterns')
    op.drop_index(op.f('ix_learned_patterns_concept_id'), table_name='learned_patterns')
    op.drop_index(op.f('ix_learned_patterns_codebook'), table_name='learned_patterns')
    op.drop_index('ix_learned_pattern_status', table_name='learned_patterns')
    op.drop_table('learned_patterns')
    op.drop_index('ix_fact_dependency_parent', table_name='fact_dependencies')
    op.drop_index(op.f('ix_fact_dependencies_parent_fact_id'), table_name='fact_dependencies')
    op.drop_index(op.f('ix_fact_dependencies_child_fact_id'), table_name='fact_dependencies')
    op.drop_table('fact_dependencies')
    op.drop_index(op.f('ix_contradictions_workspace'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_status'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_right_fact_id'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_left_fact_id'), table_name='contradictions')
    op.drop_index('ix_contradiction_status', table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_index(op.f('ix_concept_aliases_concept_id'), table_name='concept_aliases')
    op.drop_index(op.f('ix_concept_aliases_codebook'), table_name='concept_aliases')
    op.drop_table('concept_aliases')
    op.drop_index(op.f('ix_subscriptions_workspace'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_agent'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_active'), table_name='subscriptions')
    op.drop_index('ix_subscription_workspace_agent', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_shared_states_workspace'), table_name='shared_states')
    op.drop_table('shared_states')
    op.drop_index(op.f('ix_semantic_facts_workspace'), table_name='semantic_facts')
    op.drop_index(op.f('ix_semantic_facts_subject'), table_name='semantic_facts')
    op.drop_index(op.f('ix_semantic_facts_status'), table_name='semantic_facts')
    op.drop_index(op.f('ix_semantic_facts_source'), table_name='semantic_facts')
    op.drop_index(op.f('ix_semantic_facts_predicate'), table_name='semantic_facts')
    op.drop_index(op.f('ix_semantic_facts_epistemic_type'), table_name='semantic_facts')
    op.drop_index('ix_fact_subject_predicate', table_name='semantic_facts')
    op.drop_index('ix_fact_source', table_name='semantic_facts')
    op.drop_table('semantic_facts')
    op.drop_table('semantic_cache')
    op.drop_index(op.f('ix_references_workspace'), table_name='references')
    op.drop_index(op.f('ix_references_tier'), table_name='references')
    op.drop_index(op.f('ix_references_expires_at'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_receiver_knowledge_items_workspace'), table_name='receiver_knowledge_items')
    op.drop_index(op.f('ix_receiver_knowledge_items_value'), table_name='receiver_knowledge_items')
    op.drop_index(op.f('ix_receiver_knowledge_items_receiver'), table_name='receiver_knowledge_items')
    op.drop_index(op.f('ix_receiver_knowledge_items_kind'), table_name='receiver_knowledge_items')
    op.drop_index('ix_receiver_item_lookup', table_name='receiver_knowledge_items')
    op.drop_table('receiver_knowledge_items')
    op.drop_index(op.f('ix_receiver_knowledge_workspace'), table_name='receiver_knowledge')
    op.drop_index(op.f('ix_receiver_knowledge_receiver'), table_name='receiver_knowledge')
    op.drop_table('receiver_knowledge')
    op.drop_index('ix_quota_workspace_resource', table_name='quota_counters')
    op.drop_index(op.f('ix_quota_counters_workspace'), table_name='quota_counters')
    op.drop_index(op.f('ix_quota_counters_window_start'), table_name='quota_counters')
    op.drop_index(op.f('ix_quota_counters_resource'), table_name='quota_counters')
    op.drop_table('quota_counters')
    op.drop_index('ix_pattern_source_signature', table_name='pattern_source_evidence')
    op.drop_index(op.f('ix_pattern_source_evidence_source_hash'), table_name='pattern_source_evidence')
    op.drop_index(op.f('ix_pattern_source_evidence_signature'), table_name='pattern_source_evidence')
    op.drop_index(op.f('ix_pattern_source_evidence_codebook'), table_name='pattern_source_evidence')
    op.drop_table('pattern_source_evidence')
    op.drop_index(op.f('ix_pattern_candidates_trust_scope'), table_name='pattern_candidates')
    op.drop_index(op.f('ix_pattern_candidates_signature'), table_name='pattern_candidates')
    op.drop_index(op.f('ix_pattern_candidates_codebook'), table_name='pattern_candidates')
    op.drop_index('ix_pattern_candidate_rank', table_name='pattern_candidates')
    op.drop_table('pattern_candidates')
    op.drop_index(op.f('ix_ordering_counters_workspace'), table_name='ordering_counters')
    op.drop_index(op.f('ix_ordering_counters_ordering_key'), table_name='ordering_counters')
    op.drop_table('ordering_counters')
    op.drop_index('ix_model_identity_active', table_name='model_identities')
    op.drop_index(op.f('ix_model_identities_workspace'), table_name='model_identities')
    op.drop_index(op.f('ix_model_identities_receiver'), table_name='model_identities')
    op.drop_index(op.f('ix_model_identities_identity_hash'), table_name='model_identities')
    op.drop_index(op.f('ix_model_identities_active'), table_name='model_identities')
    op.drop_table('model_identities')
    op.drop_index('ix_message_sender_receiver', table_name='message_audit')
    op.drop_index('ix_message_run_created', table_name='message_audit')
    op.drop_index(op.f('ix_message_audit_workspace'), table_name='message_audit')
    op.drop_index(op.f('ix_message_audit_run_id'), table_name='message_audit')
    op.drop_index(op.f('ix_message_audit_packet_id'), table_name='message_audit')
    op.drop_table('message_audit')
    op.drop_index('ix_information_flow_object', table_name='information_flow_labels')
    op.drop_index(op.f('ix_information_flow_labels_workspace'), table_name='information_flow_labels')
    op.drop_index(op.f('ix_information_flow_labels_object_kind'), table_name='information_flow_labels')
    op.drop_index(op.f('ix_information_flow_labels_object_id'), table_name='information_flow_labels')
    op.drop_index(op.f('ix_information_flow_labels_label'), table_name='information_flow_labels')
    op.drop_table('information_flow_labels')
    op.drop_index(op.f('ix_idempotency_records_workspace'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_operation'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_expires_at'), table_name='idempotency_records')
    op.drop_index('ix_idempotency_expiry', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_federation_peers_workspace'), table_name='federation_peers')
    op.drop_index(op.f('ix_federation_peers_name'), table_name='federation_peers')
    op.drop_table('federation_peers')
    op.drop_index(op.f('ix_concepts_lsh_bucket'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_embedding_space'), table_name='concepts')
    op.drop_index('ix_concepts_codebook_count', table_name='concepts')
    op.drop_index(op.f('ix_concepts_codebook'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_codebook_releases_status'), table_name='codebook_releases')
    op.drop_index(op.f('ix_codebook_releases_release'), table_name='codebook_releases')
    op.drop_index(op.f('ix_codebook_releases_namespace'), table_name='codebook_releases')
    op.drop_index(op.f('ix_codebook_releases_merkle_root'), table_name='codebook_releases')
    op.drop_index('ix_codebook_release_active', table_name='codebook_releases')
    op.drop_table('codebook_releases')
    op.drop_index(op.f('ix_candidates_codebook'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_calibration_lookup', table_name='calibration_buckets')
    op.drop_index(op.f('ix_calibration_buckets_workspace'), table_name='calibration_buckets')
    op.drop_index(op.f('ix_calibration_buckets_task_family'), table_name='calibration_buckets')
    op.drop_index(op.f('ix_calibration_buckets_receiver'), table_name='calibration_buckets')
    op.drop_index(op.f('ix_calibration_buckets_model'), table_name='calibration_buckets')
    op.drop_table('calibration_buckets')
    op.drop_index('ix_bus_run_created', table_name='bus_messages')
    op.drop_index('ix_bus_receiver_status_priority', table_name='bus_messages')
    op.drop_index('ix_bus_partition_order', table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_workspace'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_status'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_sender'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_run_id'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_receiver'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_partition_key'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_packet_id'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_ordering_key'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_idempotency_key'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_expires_at'), table_name='bus_messages')
    op.drop_index(op.f('ix_bus_messages_correlation_id'), table_name='bus_messages')
    op.drop_table('bus_messages')
    op.drop_index('ix_agent_capability_available', table_name='agent_capabilities')
    op.drop_index(op.f('ix_agent_capabilities_workspace'), table_name='agent_capabilities')
    op.drop_index(op.f('ix_agent_capabilities_available'), table_name='agent_capabilities')
    op.drop_index(op.f('ix_agent_capabilities_agent'), table_name='agent_capabilities')
    op.drop_table('agent_capabilities')
    # ### end Alembic commands ###
